# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "javascript"
manifest_version = 2
name = "example"
service_id = ""

[scripts]
  build = "npm run build"


[[local_server.object_store.site]]
key = "%2Findex.js"
path = "src/index.js"
[[local_server.object_store.site]]
key = "mime-%2Findex.js"
data = "application/javascript"