name: CI

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: cli
    strategy:
      matrix:
        include:
        - build: x86_64-linux
          os: ubuntu-latest
        - build: x86_64-macos
          os: macos-latest
        - build: aarch64-macos
          os: macos-latest
          target: aarch64-apple-darwin
        - build: x86_64-windows
          os: windows-latest
        - build: aarch64-linux
          os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
        - build: s390x-linux
          os: ubuntu-latest
          target: s390x-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - run: rm /usr/bin/perl
      if: matrix.build == 'x86_64-windows'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Checking benches
      run : cargo check --benches

  rustfmt-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cli
    steps:
    - uses: actions/checkout@v2
    - run: rustup update stable --no-self-update
    - run: rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt --all -- --check
